### ISSUE TITLE
Lag and freezing

### ISSUE THREAD

**Issue by i-cant-git** [reupen/album_list_panel#1]
I have 1.3~ TB of music, a total of 170,000~ songs. Unfortunately this causes a lot of lag when I use this component. Especially when I use Directory structure view. The whole application freezes every few seconds.

There is heavy reading on the disk (maxing to 130 MB/s) and high CPU usage (one core is 100%) when I activate this component. Reading data and CPU usage still occurs even when "Populate on initialization" is unchecked.

The freezing or lag do not happen in Default User Interface when I use any kind of view in Album panel.

Component version: `0.3.7`
Columns version: `0.3.9.2`
Foobar2000 version: `1.3.10`

**Comment by reupen** [comment]
Sorry, I somehow missed this. 

Go to Colours and Fonts in Columns UI preferences and check if themed mode is enabled globally or for Album list panel. If it's on, try turning it off. It is known to be slow on some versions of Windows with the tree view control.

The component does not do any file I/O so I would suggest that is related to something else (e.g. artwork viewer, paging file).

**Comment by reupen** [comment]
Closing as the component does not do any direct file I/O and slowness with 'Populate on initialisation' off points to something else being the problem.
