### ISSUE TITLE
Preserve item expansion and selection state between sessions

### ISSUE THREAD

**Issue by ki-dragon** [reupen/album_list_panel#140]
Hello,

I use "by directory structure" view of Album List Panel only.
And this is actually why I'm using Album List Panel at all.
At least for me it does not save the tree status on exit of foobar.
Meaning if have several folders expanded/opened/selected then closing foobar leads to a reset of this status.
On the next foobar start all are collapsed and nothing is selected.
Is it how it should work? Is there a setting for that somewhere?

Besides, the lack of ability to select multiple folders with ctrl or shift still be the most annoying thing.

Regards

**Comment by reupen** [comment]
Preserving the state between sessions is indeed not supported at the moment. 

There is also an existing issue for multi-selection (#29).

**Comment by ki-dragon** [comment]
Thank you very much!
Discovered it working  in Columns UI 2.1.0 and Album List Panel 2.0.1 :)
