### ISSUE TITLE
a border around the text when i use color the text only

### ISSUE THREAD

**Issue by JohnnyFireOne** [reupen/album_list_panel#144]
a border around the text when i use color the text only on labumlist panel and on playlistview
i use latest albumlist panel and columsui and happends too in dev builds

may i ask for a fix or and option to make more tweakable if its by design?

![1](https://github.com/reupen/album_list_panel/assets/136648679/58a1fc61-29e0-400b-9d67-b9c7abb859c2)
![2](https://github.com/reupen/album_list_panel/assets/136648679/a0fd0c36-2df7-45fb-813e-2058e491a490)

**Comment by reupen** [comment]
Answer as per https://github.com/reupen/columns_ui/issues/751
