### ISSUE TITLE
Have the search boxes with no edges?

### ISSUE THREAD

**Issue by stephen147** [reupen/album_list_panel#22]
See here to where I'm referring.

![image](https://user-images.githubusercontent.com/14054664/79279464-044c4680-7ea6-11ea-81cf-ca0a617c967b.png)

I mean that it will have no edges shown.

**Comment by reupen** [comment]
I'm afraid there's no such option. Also, if there were no border, it would be hard to tell that it was a text box. So, it's not something I'm planning to implement, I'm afraid.

**Comment by stephen147** [comment]
No worries, I use a plugin called quick search and it has a little symbol to show that it's a search box with no edges.

Here it is in case you ever change your mind in the future.
![image](https://user-images.githubusercontent.com/14054664/79492950-ab50ef80-8018-11ea-862a-b154666cf7c0.png)
