### ISSUE TITLE
Double-click action

### ISSUE THREAD

**Issue by eddiezato** [reupen/album_list_panel#23]
Album_list_panel 0.4.0-beta7

I assigned the "double-click action to "send to playlist", but in addition to this, node expands, as if the default action "expand/collapse" is also triggered. Can you fix this?

Thanx.

**Comment by reupen** [comment]
Hi,

Thanks, I think was was a regression at some point. I'll have a look at it.

**Comment by reupen** [comment]
This is fixed in version 0.4.0.
