### ISSUE TITLE
Shift + Select bugged behavior

### ISSUE THREAD

**Issue by regorxxx** [reupen/album_list_panel#257]
Using 2.0.2 on foobar v1

Note how using Shift + Click does not properly select intended items, sometimes it removes items which should be selected, other times it selects an entirely different list of things, skips items between first and selected node, etc.
![selec](https://github.com/user-attachments/assets/df3456b6-c980-4c92-a36b-74910cdbda75)

This kind of bug is somewhat reproducible by me but not consistent. Doing the same steps sometimes works and others don't.

**Comment by reupen** [comment]
Reproduced.

**Comment by regorxxx** [comment]
Yep, can confirm I'm adding new tracks many times while foobar and the panel is open to tag/rate them, so that's perfectly possible.

There is also another bug where the view jumps to the top, without any user input (same layout and usage). But I have not been able to reproduce it (thus I didn't report it). Just reporting now in case it also has something to do with your findings.

**Comment by reupen** [comment]
You can try the build attached at the bottom here: https://github.com/reupen/album_list_panel/actions/runs/10656898604#artifacts

It should resolve Shift-select problems.

> There is also another bug where the view jumps to the top, without any user input (same layout and usage). But I have not been able to reproduce it (thus I didn't report it). Just reporting now in case it also has something to do with your findings.

I haven't seen that. The panel does try to approximately preserve the scroll position when adding and removing items, so it's possible it's related to that.

**Comment by regorxxx** [comment]
Seems to be fixed now. 

About the second issue, I will try recording it if I'm able to reproduce it.
