### ISSUE TITLE
Multiple selections using ctrl, shift and arrows

### ISSUE THREAD

**Issue by ghost** [reupen/album_list_panel#29]
The default album list panel allows to select multiple entries (albums, tracks or whatever) by just using shift + left click (everything between highlighted entries), ctrl + left click (individual entries) or the arrow keys (consecutive entries).

I have not found a way to reproduce that behavior on the UI panel, making impossible to select multiple nodes at the same time and sending them to the same playlist. 

Is there any config I have missed? Could it be considered for future releases?
Thanks.

**Comment by reupen** [comment]
Hi,

> Is there any config I have missed?

You haven't missed anything, it isn't supported at the moment, but has been asked about before.

(The background is that the panel version is a fork of the Default UI version, and that functionality was added to the Default UI version after that fork happened.)

**Comment by regorxxx** [comment]
Is there any advance on this? Is one of the the main lacking features on CUI, and most times I have to open the DUI panel just for this. Multiple selection is a must for sending things to playlists.

**Comment by ki-dragon** [comment]
Thank you very much!
Discovered it working  in Columns UI 2.1.0 and Album List Panel 2.0.1 :)

**Comment by regorxxx** [comment]
Yep, much appreciated. Fully replaces DUI panel now.
