### ISSUE TITLE
Stop horizontal auto scroll

### ISSUE THREAD

**Issue by Isabelxxx** [reupen/album_list_panel#30]
Hi,
I have found the album list panel auto scrolls to the right whenever I select a node with a name longer than the view (even if it's just a few letters).  The thing is the behavior is not consistent while navigating the library, since some items force it and others not (it gets a bit tiring for the eyes after a few times).

+blabla
     +1.blablabla
     +2.blabla
     +...

If the album list panel size is approx. equal to the end of the (2) node, then the autoscroll happens when clicking (1) but not (2). Now imagine an entire list with every item being different.

Can this behavior be disabled? The horizontal scroll bar is already disabled, so one would expect that behavior too.
Thanks!

**Comment by reupen** [comment]
Hi,

I could either add an option for it or just turn it off.

Could I check which version of Windows you are using, however? I don't think I'm seeing it when the horizontal scroll bar is turned off (on Windows 10 20H2).

**Comment by Isabelxxx** [comment]
Win 7 sP1, but I could also check it if it's working like that on other system with win 10
