### ISSUE TITLE
Album list view moves while selecting items

### ISSUE THREAD

**Issue by regorxxx** [reupen/album_list_panel#34]
I think this was reported in the past. When selecting items on the album list, if they are wider than the panel width, the view is displaced to the right automatically which becomes a mess as soon as you have items with mixed width.

The view keeps moving back and forth depending if you use the mouse, the keyboard, the item selected, etc. (see gif, specially at the end, after selecting an item it moves to right and then immediately to the left without selecting any other thing??)

A config option to force view position would be great (if it's a design choice). It produces eye strain when using the list regularly, so it would be really appreciated.

![Cui lib2](https://user-images.githubusercontent.com/83307074/129089450-047e987b-72fc-4a9f-b210-161b3be35355.gif)

**Comment by reupen** [comment]
This is the same #30 as far as I can see. Feel free to let me know if it isn't.

**Comment by regorxxx** [comment]
It's, could not find it and thought I did reported it at github, was with a previous account. Sorry.
