### ISSUE TITLE
Suggestion - Preserve the scroll position of the panel

### ISSUE THREAD

**Issue by stephen147** [reupen/album_list_panel#35]
See here attached.

![image](https://user-images.githubusercontent.com/14054664/137605848-c543f4f3-2554-4c48-bf18-22bcbcb379a8.png)

**Comment by Astro-Martin** [comment]
Retain / store the position + show last selected entry would be great !

**Comment by stephen147** [comment]
Thanks very much for adding this.

**Comment by reupen** [comment]
Probably in one to two weeks.
